### ISSUE TITLE
Radians instead of degrees in np.sin() and np.cos()?

### ISSUE THREAD

**Issue by lifangda01** [MathOnco/valis#103]
https://github.com/MathOnco/valis/blob/aa8368c7b4bf7ac79bad5c3fe170296700428603/valis/serial_rigid.py#L494-L496

**Comment by cdgatenbee** [comment]
Hi @lifangda01,
Yes, you're right, those should be in radians.  I've gone through and verified this is the only place where degrees were being passed to `np.cos` or `np.sin`. In this case it was only being used to determine the shape of a padded image that eventually gets cropped, so it shouldn't affect the accuracy of the registration. I appreciate you bring this to my attention, and I'll have it fixed in the next update.

Best,
-Chandler

**Comment by lifangda01** [comment]
Thank you for your response and the great work!
