### ISSUE TITLE
That is the difference between "towards" and "directly to"?

### ISSUE THREAD

**Issue by ciaobladoo** [MathOnco/valis#107]
Hey Chandler,

This might be an English question, but I have a hard time understanding what the *align_to_reference* parameter does. Could you explain it in another way than what has been written [here](https://valis.readthedocs.io/en/latest/examples.html#:~:text=%22HE.tiff%22-,%23%20Create%20a%20Valis%20object%20and%20use%20it%20to%20register%20the%20slides,.register_micro(max_non_rigid_registration_dim_px%3D2000%2C%20align_to_reference%3DTrue),-After%20registration%20is)?

Thanks!

Chao

**Comment by cdgatenbee** [comment]
Hi @ciaobladoo, 

Sorry for the confusion, there is probably a better parameter name to clarify what `align_to_reference` means. But, as an example, say you have 5 images you want to align, and your reference image is the 3rd one (either because you specified it by setting `reference_img_f` when initializing the `Valis` object, or valis selected it to be the reference). When `align_to_reference=False` (the default), the images are aligned serially towards the reference, i.e. 2->3 (creating the warped image, 2'), then 1 -> 2', then 4 -> 3, and finally 5 -> 4'. In contrast, when `align_to_reference=True`, the images are all aligned directly to the reference image, i.e 2->3, 1->3, 4->3, 5->3. 

I should note that during rigid registration the images are always aligned serially first, and then if `align_to_reference=True` the rigid transforms are composed serially to get each image to align more directly with the reference image. This is done because when there is a large numbers of images, some may fail to align directly to the reference image due to an insufficient number of feature matches, so this serial alignment helps get around that problem. However, in the case of non-rigid alignment, if `align_to_reference=True` then each image is truly aligned directly to the reference image (2->3, 1->3, 4->3, 5->3). When `align_to_reference=False`, the images are non-rigidly aligned serially as described above (2->3, 1->2', 4->3, 5->4').

When the set of images is small, the differences between `align_to_reference=True` versus `align_to_reference=False` will probably be small. If the number of images is large, then I think `align_to_reference=True` might be best if the goal is to create a multiplex image or transfer annotations when `reference_img_f` is specified, and `align_to_reference=False` might be better if the goal is 3D reconstruction. I hope that clarifies things, but if not, please let me know.

Best,
-Chandler

**Comment by ciaobladoo** [comment]
Thank you, Chandler, for your detailed explanation.

**Comment by ciaobladoo** [comment]
Sorry, Chandler I have a quick follow up question - if I have two images and I choose one of them as reference. Using the default behavior, does that mean the

**Comment by cdgatenbee** [comment]
Yes, that's right, the reference image shouldn't have any transformations applied to it, as long as `crop="reference"` (which becomes the default when you set `reference_img_f`). If you change to `crop="overlap"` or `crop=None`, the reference image will get padded to center it in the registered image, but no other transformations besides that would be applied.

**Comment by ciaobladoo** [comment]
Got it. Thx!
