### ISSUE TITLE
Why the inverse matrix in warp_tools.warp_xy_rigid?

### ISSUE THREAD

**Issue by lifangda01** [MathOnco/valis#108]
In the [warp_tools.warp_xy_rigid](https://github.com/MathOnco/valis/blob/aa8368c7b4bf7ac79bad5c3fe170296700428603/valis/warp_tools.py#L1819-L1844) function, the inverse matrix is used for warping the points. However in its invocations: `_warp_xy_vips` and `_warp_xy_numpy`, the forward transformation matrix is used as input to the function. I might be missing something obvious but is this intentional? 

Thanks!

**Comment by cdgatenbee** [comment]
Hi @lifangda01,
Sorry, the parameter naming here is a bit confusing. But, the reason is because in valis, the transformation matrix `M` is always estimated to find the backward transform, and the the parameter `inv_matrix` in [warp_tools.warp_xy_rigid](https://github.com/MathOnco/valis/blob/aa8368c7b4bf7ac79bad5c3fe170296700428603/valis/warp_tools.py#L1819-L1844) is just supposed to be a reminder about that. This was just to keep the behavior consistent with the image warping, which also uses the backwards transform, and so the same matrix can be passed into the functions that warp images and points. But I can see that it is a bit confusing because `M` could be called something like `inv_M` to indicate it's actually the backwards transform. Hope that clears things up, but please let me know if you have any other quesitons.

Best,
-Chandler
