### ISSUE TITLE
Reproducing Acrobat2022 Results

### ISSUE THREAD

**Issue by batukav** [MathOnco/valis#17]
Hello,

I am trying to reproduce VALIS results for the Acrobat2022 challenge. I have installed the package and just run the `acrobat_grand_challenge.py` with `-micro_reg_frac 1.0`.  In particular, I just focused on the validation image 56 and used the landmarks provided by the challenge. The results provided by the VALIS code gave me the same `p90=280.426016212` and `mean=123.027787026` values for each landmark points. On the other hand, I would expect to get different `p90` and `mean` values for each landmark and the mean of the `p90` values to give me `82.52512694556415` as announced in the Acrobat webpage. 

Maybe there are a couple of tweaks I need to make in the code but as a beginner I am not entirely sure what to do. Could you please guide me through this issue?

I also attach both landmark files, `acrobat_validation_56.csv` and `56_landmarks.csv` being the input and output landmark files.

[56_landmarks.csv](https://github.com/MathOnco/valis/files/9565899/56_landmarks.csv)
[acrobat_validation_56.csv](https://github.com/MathOnco/valis/files/9565903/acrobat_validation_56.csv)

**Comment by cdgatenbee** [comment]
Hello @batukav,
I think there may be a bug when using ```micro_reg_frac = 1.0```, which is something I'm working to fix. In the meantime, could you try using ```micro_reg_frac = 0.25```? I believe that is the value I used when submitting the validation results for Acrobat, so hopefully you will get a similar p90 value. Unfortunately my internet access is sporadic right now, but do let me know how it goes and if there is still an issue I'll double check the code to see if I can find why there is a discrepancy.

Best,
-Chandler

**Comment by batukav** [comment]
Hi Chandler,

Thanks for this prompt reply. I tried with `micro_reg_frac = 0.25` but this did not reproduce the Acrobat results either. I attach the file here for your reference. 

[56_landmarks_025.csv](https://github.com/MathOnco/valis/files/9567602/56_landmarks_025.csv)

I'll try 1-2 different things and will update you here.

best,
Batuhan

**Comment by cdgatenbee** [comment]
Hi Batuhan,

Thank you for the update, I _think_ I see what the issue is. Please correct me if I'm wrong, but it looks like the error values you're providing are based on the csv saved by ```acrobat_grand_challenge.py```.  If that's correct, then the reason those values are different than what is on the leaderboard is because the ones in the csv are calculated using automatically detected and matched image features, while those on the leaderboard are calculated using the hand annotated landmarks. The annotated H&E target landmarks were't provided as part of the Acrobat grand challenge (meaning it's not possible to calculate the statistics on the leaderboard without submitting results), so I performed the same summary statistics using matched feature points to get a sense of how valis was performing, and to also see if error calculated using automatically detected features was similar to error calculated using hand annotated landmarks. In other words, the the calculations in the csv and those on the leaderboard are based on different pairs of landmarks, and the feature distances (those in the csv) seem to be greater than the annotated distances (those on the leaderboard).

If you were calculating error differently (maybe by uploading submitting the results to the leaderboard?) and are still getting different values, please let me know. 

Best,
-Chandler

**Comment by batukav** [comment]
Hi Chandler,

Thank you for the explanation. I had confused myself with the `landmark_f` flag and the `validation_points_public_1_of_1.csv` file provided by the challenge: I had the idea the `validation_points_public_1_of_1.csv` is used to calculate the errors between registered and annotated landmarks. 

I have created an account for the challenge and uploaded my results (saved in `src_dir/acrobat/landmarks` ) there. For the image ID 56, I am getting a score of `p90 = 81.4174843264236` , whereas your submission has a score of `p90 =  82.52512694556415` . So they're much closer to each other but not the same. For this submission I have used `micro_reg_frac=0.25` as you suggested. What could be creating this difference?

best,
Batuhan
