### ISSUE TITLE
how to handle aligning images that are mirrored/flipped automatically

### ISSUE THREAD

**Issue by crobbins327** [MathOnco/valis#22]
Hi,

So I noticed that VALIS is not aligning these H&E and IF images that are mirrored/flipped.

Below are the processed images (which look good to me), and the rigid overlap that was calculated. I had to increase the max image dimension to ~10,000 because the original images are at different resolutions (0.325 MPP vs 0.5 MPP). 

Is there a feature in VALIS that can handle this case? I will try to flip the H&E image along the vertical axis and retry the image alignment, I think this will fix the problem. Just wondering if there is a VALIS parameter that I can turn on to test for mirroring/flips before finalizing the registration. Maybe there's an elegant way to test that the measured registration error is below some value or else it will test the alignment with flipping the current image along an axis?

My apologies if this is in the docs already and I just haven't found it.

![HE](https://user-images.githubusercontent.com/28576964/193157780-fe417048-0456-46d2-85df-87eee99a7e3c.png)
![IF](https://user-images.githubusercontent.com/28576964/193157794-d92538e2-113c-4ad2-9c59-0452959349d2.png)
Rigid overlap:
![HEnIF_rigid_overlap](https://user-images.githubusercontent.com/28576964/193158393-1d4140bd-d7b3-46f0-86ba-dddf3f413e63.png)
Nonrigid overlap:
![HEnIF_non_rigid_overlap](https://user-images.githubusercontent.com/28576964/193158448-02e60097-d555-4d44-ba3c-ccfa50d29b0d.png)

**Comment by cdgatenbee** [comment]
Hi @crobbins327,
At the moment, valis uses scikit-image to estimate the rigid transforms from matched features, but I'm not sure that they can account for this sort of mirroring. So, at the moment, there isn't a good way to handle this sort of situation. But it does seem like it might be possible to test for this by checking if error is reduced when including reflection in the transform. If it substantially reduces the error, then the reflection could be kept as part of the transform. I can test something like this out using these images, but I'm in the process of setting up a new laptop so it might take a little longer than usual. I'll keep you updated.

Best,
Chandler

**Comment by crobbins327** [comment]
@cdgatenbee That's sounds great Chandler! If you want the raw data I'll add a couple files for you to download in a Google drive link. 

I will also try to play with it and see if I can come up with anything. I also have the temporary solution of just flipping the image before VALIS registration which works since most of the image pairs I have are reflected. No rush.

Cheers,
Jack

**Comment by crobbins327** [comment]
I'm pretty sure the image reflection is because the immunofluorescence images are coming from a confocal fluorescence microscope whereas the brightfield microscope for the H&E is widefield. I believe that the confocal aperture causes an image reflection, similar to a pinhole camera. So this would likely be the case when aligning serial sections of tissue for widefield and confocal WSIs.  

Maybe this should be a default option to start calculating the alignment from a reflected image when this is the case? (e.g. reference is confocal, current image is widefield) But I don't think this is stored in the OME-TIFF metadata for our files, so it probably just needs to be a default option in the registrar that can be turned on based on the problem. 

I can compress the files to be ~10GB in total if you are interested. Just let me know.

**Comment by cdgatenbee** [comment]
Hi @crobbins327, 
I added some tests that will determine if the alignment is improved after reflecting the images along the x and or y axes. However, it's an option that has to be set when initializing the `Valis` object, which is done by setting `check_for_reflections=True`. I made it optional for now because it requires repeating the process of feature detection and matching for each variant of the image, and so can be time consuming and maybe not necessary all of the time. Anyhow, I tested it with the images you provided, and here are the results I got:

Original:
![images_original_overlap](https://user-images.githubusercontent.com/27818843/200865367-08ce202f-888e-4687-b859-000d3ff4bd09.png)

Rigid registered:
![images_rigid_overlap](https://user-images.githubusercontent.com/27818843/200865530-683fd743-34d2-4128-8da6-8784a42c2d97.png)

Non-rigid registered:
![images_non_rigid_overlap](https://user-images.githubusercontent.com/27818843/200865589-d6056dec-cd25-409a-899f-4ed2f215d440.png)

I don't have any other images to test this with, so please let me know if you run into any problems and we can reopen this, but I'll close it for now.

Best,
Chandler

**Comment by crobbins327** [comment]
@cdgatenbee This is perfect, thank you Chandler! Looking forward to testing it out and digging into the code to see how you solved this problem. :)

Thank you again for this awesome repo!
