### ISSUE TITLE
not enough points to transform

### ISSUE THREAD

**Issue by NicolasNerr** [MathOnco/valis#24]
Hello ! 

Is there any set of parameters that it is possible to tweak when not enough matches are found to perform rigid/non-rigid transformations? 
Does lowering the resolution even more can work ? 

Thank you, 
Best regards

**Comment by cdgatenbee** [comment]
Hi @NicolasNerr,
Glad to see you were able to resolve the installation issues. On this issue, there are a few things you could try. Lowering or even increasing the resolutions is a good place to start. Maybe try setting ```max_processed_image_dim_px``` to values between 500 and 2000 when creating the ```Valis``` object. Another easy thing to try would be to set ```create_masks=False``` when initializing the ```Valis``` object, since it could be that the masks valis creates are removing too much of the image, and potential matches are lost. This can be checked in the "masks" folder, where the region where the features are being detected will be outlined in green. If neither of those work, you could also try some different preprocessing methods. What sorts of images are you working with? 

Best,
Chandler
