### ISSUE TITLE
AttributeError: vips_image_hasalpha

### ISSUE THREAD

**Issue by q1nwu** [MathOnco/valis#29]
Thank you for your work and the open-source method, it is greatly appreciated.

I found error running the examples/register_ihc.py.
AttributeError: vips_image_hasalpha

Do you have an idea on what is the issue here ?
Thank you so much.

**Comment by cdgatenbee** [comment]
Hello @q1nwu,
Apologies for taking so long to get back to you. Based on the error, it looks like libvips and/or pyvips may need to be updated. I think this because `vips_image_hasalpha` is function from pyvips.vips_lib, which gets called by pyvips.Image. hasalpha [(source)](https://libvips.github.io/pyvips/_modules/pyvips/vimage.html#Image.hasalpha), so it may be possible that the version of libvips or pyvips you are using is prior to the current version that has these functions. Please trying updating and if you're still having the error please let me know.

Best,
-Chandler

P.S. Happy New Year!
