### ISSUE TITLE
H&E deconvolution pre-processing

### ISSUE THREAD

**Issue by aelskens** [MathOnco/valis#41]
Hi Chandler,

Are you interested in a pull request to implement an H&E deconvolution and normalization pre-processing based on the work of Macenko et al. ([2009](https://doi.org/10.1109/ISBI.2009.5193250))?

Best,
Arthur

**Comment by cdgatenbee** [comment]
Hi @aelskens, 
Thank you, that would be great to have that available! So yes, please, submit a pull request and I'll work on merging it into the next update. 

Best,
-Chandler

**Comment by zindy** [comment]
Hey @aelskens, @cdgatenbee 

There are programs (or libraries) you can use to determine the stain vectors, e.g. [QuPath](https://qupath.readthedocs.io/en/stable/docs/tutorials/separating_stains.html), [scikit-image](https://scikit-image.org/docs/stable/auto_examples/color_exposure/plot_ihc_color_separation.html), [HistomicsTK](https://github.com/DigitalSlideArchive/HistomicsTK/tree/master/histomicstk/preprocessing/color_deconvolution). However, a way to give VALIS a stain vector for the dye you wish to use in your alignment would be really useful indeed (if not already implemented).

Same for fluorescent images, I need to check in the docs if it is already possible to specify a particular channel (same again, if not implemented already).

The cases I have in mind where I think aligning nuclei would help:
* Two HDAB slides with different markers where the DAB staining almost looks complementary between the slides
* One HE slide, one fluorescent, aligning the haematoxylin deconvolved channel on one and the DAPI channel of the other.

Just thinking with color deconvolution, would VALIS (pyvips?) cope with floating point intensities? I need to check the docs and the code before making suggestions! ;-)

Cheers,
Egor

**Comment by cdgatenbee** [comment]
Hi @zindy, 
Thank you for the suggestions! In the past I had avoided color deconvolution because I was primarily working with dual stained images (DAB + Fast Red) that had a great deal of spatial variation in staining intensity, and so the deconvolved images looked very different from one another, and the registrations ended up being pretty poor. But I think stain deconvolution could be quite helpful in the cases you suggest, as well as when all the images are H&E. @aelskens, will your processor be specifically for H&E, or more general, being able to "find" the different stains? If the former, maybe we could also create a more generalized processor to automatically calculate the stain matrix, possibly using one of the packages suggested by @zindy?

Regarding fluorescent images, valis does have a [ChannelGetter](https://valis.readthedocs.io/en/latest/preprocessing.html#valis.preprocessing.ChannelGetter) pre-processor that will extract a channel from an image, based on the channel names in the metadata. By default it looks for a DAPI channel, but it could be changed to something else. Also, the default feature detectors and non-rigid registration methods are from opencv, and it seems that they only really work with uint8 images (at least when testing with the BRISK feature detector). To get around this, prior to feature detection valis scales the image to 0-255 (based on the processed image's min and max) and then converts to uint8. There may be a better way to handle this, but for now it lets valis work with float images. As far as pyvips goes, I don't recall running into any issues with float images, so I think it should all work ok :) Thanks again for your help and suggestions!

Best,
-Chandler

**Comment by aelskens** [comment]
Hi @cdgatenbee,

Regarding your question, the proposed method can be used to normalize and separate the two stains from H&E images into different channels. It can also be used to extract the hematoxylin stain in IHC images since it is used for counterstaining. However, it cannot extract the DAB stain. Despite this limitation, it can still serve as a useful foundation for a more general implementation of color deconvolution in the future.

By the way, I want to inform you that I am currently testing my implementation to ensure its validity. I plan to submit a pull request tomorrow for your review.

Best,
Arthur

**Comment by aelskens** [comment]
Hi @cdgatenbee,

No worries, thanks for letting me contribute!

Arthur
