### ISSUE TITLE
rigid registration not working

### ISSUE THREAD

**Issue by matthiaskoenig** [MathOnco/valis#68]
Hi all,
rigid registration is failing for the attached example, i.e., the HE stain is not aligned with the H-DAB stains. This worked for all other animals, but fails here. I can share the slides tomorrow.

[rat_NOR-25.zip](https://github.com/MathOnco/valis/files/12318011/rat_NOR-25.zip)

**processed**
![J-12-00356_NOR-025_Lewis_HE_Run 06_ML, Sb, rk_MAA_003 (2)](https://github.com/MathOnco/valis/assets/900538/849ce314-67a4-4f2f-b57e-28cbee0b0298)
![NOR-025_Lewis_J-12-00356_CYP3A4 1 1000_Run 12_ML, Sb, rk,Lung_MAA_005](https://github.com/MathOnco/valis/assets/900538/37bc5a4b-637d-42a7-b8c2-2c7b00a56cf0)

**rigid registration**
![0_J-12-00356_NOR-025_Lewis_HE_Run 06_ML, Sb, rk_MAA_003 (2)](https://github.com/MathOnco/valis/assets/900538/976ecf38-44b2-409d-a670-9acf2d96fe3c)
![1_NOR-025_Lewis_J-12-00356_CYP3A4 1 1000_Run 12_ML, Sb, rk,Lung_MAA_005](https://github.com/MathOnco/valis/assets/900538/4ef2cb59-4daa-486a-9bdb-61c910b74ab4)

The masks look strange for some of the images. 
Also the HE arrangement of the tissues is very different then the H-DAB. Are there any setting to register the images with Valis?

Best Matthias

**Comment by cdgatenbee** [comment]
Hi @matthiaskoenig, 
Glad to hear valis worked with most of the images, but I think the reason the image `J-12-00356_NOR-025_Lewis_HE_Run 06_ML, Sb, rk_MAA_003 (2)` isn't aligning is because it looks like the triangular tissue got moved to the opposite side of the circular tissue (when compared to all of the other images). The "overlap" images that valis creates are cropped to where the images overlap, so they don't show where the triangular shaped piece would be after alignment, which I think helps visualize why this image isn't working. However, the uncropped overlap image would look something like this:

![gh_issue_68](https://github.com/MathOnco/valis/assets/27818843/92cc9ff7-b066-4f8a-994e-6dd4792d10e7)

So you can see that in that image it looks like the triangular shaped tissue looks like it moved to the opposite side of the circular piece. Since valis aligns the image as whole, and not necessarily individual pieces, I don't think valis will be able to  to move that triangular tissue back to the other side of circular piece. Having said that, with some custom code (using an `ImageProcesser`), it might be possible to mask out each region, and then align those individually, i.e. having one registration for the circular region, and one for the triangular region. Do you think something like that would work?

Best,
-Chandler

**Comment by matthiaskoenig** [comment]
Thanks. This is perfect. 

I assumed valis is figuring out the main pieces (e.g. Othsu filtering) and tries to align all pieces as good as possible. We will do preprocessing and align the individual tissue sections.
Best Matthias
